version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql-5.7
    volumes:
      - ./db:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
    environment:
      - "MYSQL_ROOT_PASSWORD=pass"
      - "MYSQL_DATABASE=mysql"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
